### ISSUE TITLE
Problem connecting to Siemens S7-400

### ISSUE THREAD

**Issue by sekulicb** [Peter-B-/Sharp7.Monitor#1]
When trying to connect to newer PLCs such as S7-1500, I have no problems by just suppling ip address and DB value, but when I try to do the same with S7-400 I get the following error:

![image](https://github.com/user-attachments/assets/962e1921-7706-43fb-893d-5b2096e279d7)

I'm thinking that we need to manually pass in the "type" of PLC. We use TIA Portal and for that PLC, there is no options to check "Permit access with PUT/GET communication" since it's older version.

![image](https://github.com/user-attachments/assets/6dbc7a70-06ec-4edc-83f6-19a9651ca1a8)

What could be potential workaround for this situation?

**Comment by Peter-B-** [comment]
Hello @sekulicb and apologies for the late reply.

The Sharp7.Monitor uses Sharp7, which in turn uses [Snap7](https://snap7.sourceforge.net/) by Davide Nardella. Snap7 is definitly compatible with S7 400, and so Sharp7.Monitor should be. But I have to admit, that I'm a C# developer and do not have detailed knowledge about configuring S7s. Maybe you can find some hints on the configuration in the [Snap7 documentation](https://snap7.sourceforge.net/) or the Snap7-Refman, which is part of the [download](https://sourceforge.net/projects/snap7/files/1.4.2/).

Sorry that I can't be of further assistance here. 

Kind regards
Peter
